name: ${SERVICE_NAME}-infra

services:
  web:
    image: daniel101/${SERVICE_NAME}:${IMAGE_VERSION}
    restart: always
    ports:
      - "3007:80"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 256M

