name: Build Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Use Node 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build